noisetorch/NoiseTorch

main.go
Added the necessary flags to use Noisetorch without spawning an interface:
* `-u`: Unload a suppressor, if already running
* `-t`: Set voice activation threshold (default 95)
* `-s`: Supply a default PulseAudio source name
* `-l`: List available PulseAudio sources by ID, with source name attached
resolves #37
=> Add ability to bypass UI

config.go, main.go, ui.go
Implementation for https://github.com/lawl/NoiseTorch/issues/66
As per last comment https://github.com/lawl/NoiseTorch/issues/66#issuecomment-740107475
UI
```
Is there a last used device stored in the config?
Y: Try to preselect that
Available: good, we're done
Unavailable: preselect pulseaudio default device
N: preselect pulseaudio default device
```
Cli
```
Device passed as parameter?
Y: Try use that, if unavailable, error out.
N: use pulseaudio default device
```
The last used input id is stored in the config when noise torch is loaded
My go knowledge is a bit rusty as I haven't written any line of go in a few years so let me know what can I improve.
Naming is a bit confusing as I don't really have any experience with pulse audio so I'm not sure what the difference between …
=> Load pulse audio default input and store last used input in the config file

main.go
The pull request switches to 24-hour notation for log file name timestamps.
=> Use 24-hour clock when adding timestamps to log file names.

cli.go
Error messages were not printed to stderr. Fixed it by using
fmt.Printf() instead of log.Printf().
=> Fix not printing errror message

Makefile
While in the process of writing an `ebuild` for Gentoo's [GURU](https://github.com/gentoo/guru/) overlay, the installation raises a warning of the style `warning: jobserver unavailable: using -j1` whose solution [is this one](https://stackoverflow.com/questions/60702726/warning-jobserver-unavailable-using-j1-add-to-parent-make-rule). This is a simple change to implement it.
Thanks for this project!
PS: the information above and the one liner are a courtesy of @thesamesam
=> Makefile: use $(MAKE) instead of directly using make

.github/workflows/golangci-lint.yml
`golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports `yaml` config, has integrations with all major IDE and has dozens of linters included.
In this current configuration it will ignore existing issues in pull-requests and only report on new issues introduced in a PR.
When pushing directly to the main branch it will most probably report all the existing issues.
=> feat(ci): run golangci-lint action

.github/workflows/flawfinder.yml
Same as with the other PR from earlier: take your time, this won't run away.
....
Here is another idea for regularly scanning the C code for probable issues: [flawfinder](https://dwheeler.com/flawfinder/) 
> [...] flawfinder, a simple program that examines C/C++ source code and reports possible security weaknesses (“flaws”) sorted by risk level. It’s very useful for quickly finding and removing at least some potential security problems before a program is widely released to the public.
Scanning results with be shown in the pullrequest checks section:
as well as the security tab of the project:
So they will provide a good overview on possible improvements.
Though not all the findings have to be valid issues. Some may be conscious decisions - for example those complaints, that something can …
=> feat(ci): add flawfinder action

.gitignore, README.md, ui.go
Just some minor cleanups that I noticed while looking at some other code in the UI.
* Add Sublime Text to .gitignore: if others use Sublime as well it may be worth committing the .sublime-project file to the repo, the Sublime gitignore recommends it in that case but I don't feel too strongly either way.
* Fix URLs in README to point to the noisetorch org.
* Fix URL in About->Source Code to point to the noisetorch org.
=> Minor Cleanups

.github/workflows/build-artifact.yml, .github/workflows/release.yml, Makefile, scripts/signer.go
* disable update mechanism
* remove upx (can later be added again, if need be)
* generate dev binary and upload to pull_request
closes #272
=> automatic release to GitHub

ui.go
Fixes https://github.com/noisetorch/NoiseTorch/issues/158. When both of the filters are disabled and unloaded, "Noisetorch unconfigured" will be shown in light blue. This should clear up some user confusion in this case.
=> fix: Don't show loaded when both filters are disabled

ui.go
Kind of a small corner case fix for a problem I noticed while working on a different ui problem. When Display Monitor Sources is unchecked and no mic is plugged in, if Filter Microphone is checked, Load NoiseTorch will be available with the monitor source as the "checked" element, even though it is hidden. This small modification to the check in inputSelection() fixes this bug.
Also removes a set of unnecessary parenthesis in an if.
=> fix: Make input selection aware of if "Show Monitor Sources" is checked

ui.go
As suggested in https://github.com/noisetorch/NoiseTorch/pull/286. When filtering is selected but a device to filter isn't, show unconfigured rather than inactive. I more or less borrowed the logic for determining if the Load button should or shouldn't be shown, made it into a helper function, then made it be used in both cases.
I was somewhat on the fence about this but have come around to liking it.
=> fix: When filter is selected but no device is selected show unconfigured

cli.go, update.go
This fixes https://github.com/noisetorch/NoiseTorch/issues/316
Any feedback welcome. Even if nit-picky.
=> fix(updates): Add error handling to getLatestRelease()

README.md
Instructions on how to install the software if you build from source
=> Install instructions for source build

views.go
I've reimplemented views using a slice because I though the current implementation using an array of an arbitrary size could be better, especially because it was wasting space as a means to avoid a buffer overflow. I've also removed mutexes because this code is never called in a concurrent way and I don't see any reasons why it would be in the future. 
Errors are now managed using `log.Fatal` which I dislike because the program may exit without the error message being printed to the console, but it's used all over the place in NoiseTorch's source code. In the case of views, these errors should never happen, unless a programmer did something wrong in the UI code like mistakenly closing two views when there was only one existing. 
Again, any feedback welcome, even if nit-picky.
=> chore(views): Reimplement views using slices

Makefile, cli.go, update.go
for comparing the version strings with semver (and only there), we need to strip the 'v' prefix from the version strings.
=> fix(update): strip 'v' from version string

README.md
Some distros still choose to use ~/.icons and symlink ~/.local/share/icons to that directory. A normal untar will overwrite that path.
=> chore(readme): update README tar to follow symlinks

.github/ISSUE_TEMPLATE/bug_report.md, LICENSE, Makefile, README.md, c/ladspa/module.c, capability.go, cli.go, config.go, main.go, module.go, rlimit.go, ui.go, update.go, views.go
* Remove references to NoiseTorch throughout the UI
* Add a way to add a suffix to the end of the program name to indicate things such as a third-party or dev build
* Add a way to set a custom website url (i.e. AUR url)
This is really a two-parted thing: many references to NoiseTorch have been removed, which will make changing the name easier, as well as make it easier for third-party packagers to deal with the license. Adding the ability to set a suffix, as well as a custom url, will hopefully also help in the marking of third-party builds.
I'm making this as a draft, as this needs to be tested with pulseaudio as the backend to ensure I didn't break anything on the pulseaudio front. Things seems to be working as expected on the pipewire side of things.
I'd appreciate it if someone who …
=> Remove references to NoiseTorch

update.go
Fixes #345
#345 stemmed from a Nixpkgs issue, where the author saw a timeout message while checking for updates: https://github.com/NixOS/nixpkgs/pull/179088#issuecomment-1167959829
This is actually due to this module-level function call, which calls out to github to check the latest current release.
https://github.com/noisetorch/NoiseTorch/blob/ebf595ba4bf4c8143b1c60b0a787e144dede5824/update.go#L81
This moves the function call to an `init()` function, so we can avoid this check entirely if updates have been disabled through build variable.
- I can build and run the program with `UPDATE_URL` both as normal and empty in the `Makefile`
- I ran `gofmt`
=> Do not check latest release if updates disabled

cli.go, main.go, module.go, ui.go
I attempted to re-implement all of the code (outside of `ui.go`) that was marked as needing re-implementation.
I only used the *TODO* comments and what I can discover just from using NoiseTorch to figure out what the missing code blocks are supposed to do.
=> Cleanroom re-implementations for deleted code

cli.go, main.go
Under PulseAudio, the user-friendly name for each audio device was
stored under its `device.description` property. Under PipeWire,
`device.description` is the name of the sound card, not the source/sink.
This results in all source devices showing their sound card's name in
NoiseTorch. Since I have multiple sources on the same sound card, it
meant all my microphones had the same name, making NoiseTorch unusable.
This commit changes the assignment of device names. When running under
PipeWire, the `pulseaudio.Source.Description` field holds the correct
device name, while the
`pulseaudio.Source.PropList["device.description"]` field that was being
used previously is the sound card's description.
The NoiseTorch context must now be passed to the `getSources` and
`getSinks` functions so they can …
=> Fix naming of audio devices under PipeWire

README.md
If the `~/.local/bin` directory doesn't exists (was the case for me on POP OS) the cp command will copy the noisetorch binary to `~/.local/bin` and not into the folder (`~/.local/bin/noisetorch`)
=> docs: create ~/.local/bin dir

assets/noisetorch.desktop
Some application launchers will fallback to the comment if a generic name isn't provided, so this change adds a generic name. This makes it more consistent with other applications a user may have.
Before:
After:
=> Add a generic name to noisetorch.desktop

main.go
Given that the server version is not a proper `major.minor.patch` format, 
example: `16.0`
then the version parsing fails.
To avoid this, Added a fallback version regex, so that if the actual regex fails then we check with the fallback version regex,
further since the server version does not contain the patch number setting the patch number to `0` by default.
Something I found while going through the pulseaudio repo, as per my understanding they might be creating `major.minor` style tags for dev or testing.
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/git-version-gen?ref_type=heads
Closes #339
=> Handle missing patch version by making it optional in regex matching. 
